name: Meu Blog
description: >
    Um blog feito para compartilhar dicas, estudos, projetos, códigos e idéias.
about: >
    15 anos de experiência na construção de projetos de Software. 
    Liderou uma série de projetos em .Net utilizando metodologias agéis (scrum).  
    Possui interesse em novas tecnologias, ciência de dados, empreendedorismo e criação de produtos inovadores.  
    Criou um aplicativo que já tem mais de um milhão de downloads - BoaLista.  
    Formado em engenharia de computação pela PUC RJ e  pós graduação em gerência de projeto de software pela PUC RJ. 
 

master_repo: false
url: "https://fabio-neves.github.io/"
markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
plugins_dir: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

page_excerpts: true
excerpt_separator: <!--more-->
logo:             img/dr_scripto.gif
disqus_shortname: fabio-neves

rtl: false
owner:
  name:           Fábio Neves de Souza
  avatar:         "https://avatars2.githubusercontent.com/u/8528791?s=460&v=4"
  email:          "fabionevesdesouza@gmail.com"
  # Social networking links used in footer. Update and remove as you like.
  twitter: souzinha
  github: https://github.com/fabio-neves
  stackexchange: https://stackoverflow.com/users/1846514/souza?tab=profile
  linkedin: https://www.linkedin.com/in/fabionevesdesouza/
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
